### ISSUE TITLE
support multiple gdrive accounts

### ISSUE THREAD

**Issue by helal00** [google/skicka#73] opened 2015-04-24 17:28 UTC
-tokencache=filename
any file name, even ~/.skicka.tokencache.json , is throwing the following error:
skicka: error creating Google Drive client: OAuthError: CacheFile.PutToken: open : no such file or directory

-config=filename is silently ignored in favor of default config if not used with -tokencache

when used both options, the above error was thrown.

The issue is with https://code.google.com/p/goauth2 library, which is already deprecated in favor of https://godoc.org/golang.org/x/oauth2

anyway to avoid this error?

**Comment by mmp** [comment] 2015-04-24 18:46
Can you try and see if it works for you if you use `-tokencache filename` (i.e., with a space instead of an equals sign)? I think the issue is that skicka is no longer trying to do tilde expansion on its own.  (And then I think it's better to just not support the "=" syntax, rather than duplicating that functionality with the shell.)

**Comment by helal00** [comment] 2015-04-24 19:15
I tried with absolute path, without = sign as you suggested and with = sign also, same result in all cases.

**Comment by helal00** [comment] 2015-04-24 21:16
My bad!! actually this was some kind of bash scripting typo. These options are working fine. But the metafile needs to be deleted on every new gdrive account added.

Thanks

**Comment by mmp** [comment] 2015-04-27 17:37
Ok, great on the options working!

Can you describe in some more detail your usage case for using multiple gdrive accounts is? The system doesn't really support that well now (as you've discovered), but if you can say more about what you're trying to do, it would likely be possible to improve it in this respect...

**Comment by helal00** [comment] 2015-04-28 07:42
Any user can easily opted to use Google's free 15 GB space multiple times. As a user can create multiple accounts with little or no restrictions, they will surely be interested using 'skicka' for multiple accounts. This is also true for me. I usually backup my laptop or desktop data to different accounts of google drive, as 15 GB is not sufficient. Those data backup is only for disaster management.


The problems I am facing right now with 'skicka' is:
1) It takes long time (~1.5hr )to sync (uploading) a long diretctory tree (~600MB). 
2) ~/.skicka.metadata.cache file need to delete almost every timqae you use a new -config and -tokencache file. You have to oauth2 verifification for the default config files first, then for the custom config. If you do opposite, you have to delete the metadata file first to get any custom config access the drive.

To oevercome these limitations, 'skicka' should use a different  metacache file for every new custom config. There might be a option -metacchefile or so.

To decrease the syncing time the meta data cache file should be used more effectively. I didn't see the code yet, how you people did it though, but I think the first sync for a location could take time, that’s reasonable. But the subsequent syncs should only fetch the changes list after the last sync time from the Google drive (Last time I saw, there is a way in drive api to get the change list only after or before a time period). Then this list should be compared with local Directory change list and upload or download only the changes. The local and remote listing process should run simultaneously in different threads.

Any way, thanks for the efforts you people put here to make it workable. I didn't came access any such working thing yet. TC.

**Comment by mmp** [comment] 2015-04-28 15:53
Ah, yes, there actually already was a -metadata-cache-file option (but it wasn't documented :-( ).  That's now fixed.  If you have multiple accounts, and if you specify a separate -config, -tokencache, and -metadata-cache-file for each of them, then you should be able to seamlessly switch between accounts.

The metadata caching is implemented as you describe--it only gets the new changes, so is generally pretty fast after the first sync. You may not be seeing this behavior if you're trying to use the same file over multiple accounts (or for that matter, are removing it each time you switch accounts.) Let me know if you see better behavior on that front once you switch to using -metadata-cache-file to specify different caches for each account...

**Comment by helal00** [comment] 2015-06-27 08:26
ah yeah, now the behaviour improves a lot. And the subsequent syncing is also pretty quick. Keep up the good work.

**Comment by mmp** [comment] 2015-06-30 00:42
Ok, great! Closing this out.

**Closed by mmp** 2015-06-30 00:42 UTC
