### ISSUE TITLE
potential race condition with large upload tasks

### ISSUE THREAD

**Issue by pnu** [google/skicka#45] opened 2015-01-12 08:33 UTC
There seems to be a concurrency related issue with large uploads.

I have a large upload task of ~60k files and 100GiB total size. I have done >10 of attempts to upload this, and it has always failed at some random point during the upload. The upload stops to error `skicka: …filename…: googleapi: Error 404: File not found: …id…, notFound` or `couldn't run Google Drive query: googleapi: Error 400: Invalid Value, invalid`. I've always started a new upload (ie. to a new, non-existing Drive path), since getting the list of files of an interrupted download is very slow. Also, the creation of all paths (the first step in upload) succeeds, the error happens when actually uploading the file contents.

After suspecting this, I have tried with both higher and lower `nWorkers` values. With higher values it seemed to die earlier, and with value `1` the transfer succeeded in first attempt:
```
106.30 GB / 106.30 GB [=====================================] 100.00 % 71h15m39s
skicka: preparation time 0s, sync time 71h 15m 55s
skicka: updated 58121 Drive files, 0 local files
skicka: 0 B read from disk, 0 B written to disk
skicka: 106.30 GiB uploaded (434.44 kiB/s), 0 B downloaded (0 B/s)
skicka: 129.20 MiB peak memory used
```

Unforunately this is hard to reproduce exactly. The skicka version was ac702d253ea3389ec71c41a2f85f218b1397e8d5 .. this version reproduced both error cases above and the final success (with `nWorkers := 1`).

**Comment by mmp** [comment] 2015-01-12 16:50
It is possible that this is related to issue #12, rather than being a race condition (though it may be a race as well!).

Are any of the files you're uploading large (>1GB or so), and is it failing on large files? What can happen with large files is that, after an hour the authorization token automatically expires, and the regular Google Drive API upload call doesn't allow updating the token in the middle of an upload. What could be happening is that with 4 workers, then they are all fighting for bandwidth and the big files don't finish in an hour, but with 1 worker, the big files can get through.

There's an experimental skicka branch (chunked-uploads) that uses Google Drive's "chunked" upload API, which also allows token refresh in the middle of uploads.  I'll test that a bit today and see if I can get it merged, to see if that helps, pending more information about the above.  If the failures you're seeing are on smaller files, then this will take some more digging. :-)

**Comment by pnu** [comment] 2015-01-12 18:12
Ok, this sounds possible. I don't know which file is failing, but I have 2 files ~2GB. Rest of the largest files are under 1GB. I have some of the old (failed) transfer attempts still stored in the Drive. Searching for the 10 largest files' names shows that they are only present in the successful upload target path. However, I don't know it it's just that the largest files are transferred last?

OTOH, I have quite decent uplink speed, so the 2GB file takes about 2.5 minutes to upload. Just tested with the largest file I have in that set:
```
skicka: Getting list of files to upload... Done. Starting upload.
1.93 GB / 1.93 GB [============================================================================================================================] 100.00 % 2m24s
skicka: preparation time 0s, sync time 2m 24s
skicka: updated 1 Drive files, 0 local files
skicka: 0 B read from disk, 0 B written to disk
skicka: 1.93 GiB uploaded (13.63 MiB/s), 0 B downloaded (0 B/s)
skicka: 2.39 MiB peak memory used
```

**Comment by mmp** [comment] 2015-01-15 05:12
Nice uplink bandwidth!

I've reviewed the code for possible races and done a bunch of tests, including some with the go race detector (and have done so with a fast uplink), and haven't been able to reproduce this.  The fact that you can upload 2GB in a few minutes suggests that the issue isn't that the authorization token is expiring.

In the next day or so, I'll be landing the changes to skicka that use the resumable upload API for large files; my hope is that this will fix this issue for you.  (Though I'd still like to figure out the root cause.)

If you still see the issue with those changes, then we can see if we can get some tracing data that can give some more insight...

**Comment by mmp** [comment] 2015-01-16 00:54
As of e8f2736003288da377c8192e63f476c940bb0f3e, resumable uploads for large files are checked in; if you have a chance to try it, I'd be curious to know if this fixes the issues you're seeing.

**Comment by pnu** [comment] 2015-01-16 09:10
Great, thanks! I've just started a new upload test with that version. I'll report back asap; The directory creation takes 8..9 hours (btw, it's great to have a separate progress indicator for that!), before we get to the upload stage..

**Comment by pnu** [comment] 2015-01-19 08:25
Ok, I had two transfers running at the same time, with same source folder: one was running ac702d253ea3389ec71c41a2f85f218b1397e8d5 .. modified so that nWorkers was set to 1 (as described above). This worked:

```
skicka: Getting list of files to upload... Done. Starting upload.
106.43 GB / 106.43 GB [=====================================] 100.00 % 66h39m47s
skicka: preparation time 0s, sync time 66h 40m 22s
skicka: updated 58611 Drive files, 0 local files
skicka: 0 B read from disk, 0 B written to disk
skicka: 106.43 GiB uploaded (464.95 kiB/s), 0 B downloaded (0 B/s)
skicka: 125.04 MiB peak memory used
```

The other was running e8f2736003288da377c8192e63f476c940bb0f3e (not modified). This had several issues during the "files"-stage (ie. when uploading, not during directory creation) and finally died to an API error.

During the transfer I got some of these:
`skicka: …local file path…: googleapi: Error 404: File not found: …drive id…, notFound`

And dozens of these - all these failures seemed to be happening to large files:
`skicka: …local file path…: giving up after 6 retries: rate limit exceeded`

However, there was no other error output, and the transfer continued, until it finally died to this:
```
Files: 58.53 GB / 95.70 GB [=====================>-------------] 61.16 % 4h36m0s
2015/01/18 04:35:47 couldn't run Google Drive query: googleapi: Error 400: Invalid Value, invalid
```

**Comment by mmp** [comment] 2015-01-21 23:52
Ugh, that's pretty bad! Just to confirm, you were uploading to different destination folders, right?

Running two transfers at once is likely to cause Google Drive to issue more errors due to rate limits, but on the other hand, skicka should be as robust as possible to that case--that definitely doesn't excuse the errors.

I have a few ideas for changes that may help with this; I'll try to test them out in the next few days.

Thanks for your patience with this.

**Comment by pnu** [comment] 2015-01-22 12:59
Yes, I was uploading to separate destination folders on My Drive.

**Comment by mmp** [comment] 2015-03-16 00:41
Is there any chance you could retry this with the most recent version of skicka?  I still have yet to find any races, but the upload code has been improved substantially, so I'm hopeful/curious to know if things works well now.

If it still fails, if you could do a run like "skicka -debug upload /src/path /dst/path" and send the debugging output, that'd be a huge help.

Thanks!

**Comment by mmp** [comment] 2015-04-23 16:17
Closing this out, under the thinking that the upload code has changed a lot since this was originally reported, and no similar issues have been reported.

**Closed by mmp** 2015-04-23 16:17 UTC
