### ISSUE TITLE
Memory high peak with drive contain a lot of files

### ISSUE THREAD

**Issue by Namke** [google/skicka#114] opened 2017-03-09 03:32 UTC
Hello
Here the situation
- During initialize or completion (of uploading, listing file whatsoever) skicka take likely 13-16GB of RAM.
- During uploading, skicka take 10-11GB of RAM.
This is not an actual issues but I guess this because skicka loaded all file list into memory, is there are any method to put file list into some sort of database (sqlite?) to reduce memory mapping during action?

**Comment by seadog007** [comment] 2017-03-10 18:34
It is totally same as #112

**Comment by mmp** [comment] 2017-03-16 00:38
Closing as a dupe of #112. (Agreed that this would be a good to fix at some point!)

**Closed by mmp** 2017-03-16 00:38 UTC
